import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, ButtonGroup, Link } from "@chakra-ui/react";
import { useRouter } from "next/dist/client/router";

const Test = () => {
  const router = useRouter();
  const handleClick = () => {
    router.push("/todo");
  };
  return (
    <div>
      <Button colorScheme="blue" onClick={handleClick}>
        Button
      </Button>
    </div>
  );
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Test />{" "}
        <div>
          <Link href="todo">Go To Todo</Link>
        </div>
      </main>
    </div>
  );
}
